Deduplicate some client functions
mercadopago/sdk-python pull request #49
Opened 2021-09-13 17:09 UTC by WhyNotHugo

A few of these functions were pretty much a copy-paste of each other, so
I've de-duplicated these and just re-use the same block for all of them.

This improves readability a bit, and makes it a bit more obvious that all
of these actually do the same (I really came across this trying to understand
a bit better how some internals of the SDK work).

I've also deleted an initialiser that did nothing, since that mostly adds
noise/complexity.

2021-09-13 17:09 UTC, WhyNotHugo commented
I tried to stick to the existing code-format convention, though I'd
recommend you have a look at black, which is pretty much the de-facto
standard in Python-world and produces pretty standard formatting. I'm
mostly mentioning this because it was a bit tricky to hand-craft the
formatting when making these edits.

If you consider it a welcome change, I can send a sample PR setting up
black+pre-commit to handle this automatically.

2021-09-15 14:05 UTC, rhames07 requested changes

2021-09-16 20:12 UTC, WhyNotHugo commented on mercadopago/http/http_client.py
> +            api_result = session.request(method, url, params=params, headers=headers, timeout=timeout)
:facepalm: You're very right. Fixed.

2021-09-17 12:45 UTC, rhames07 approved these changes

2021-09-17 13:08 UTC, merged