add chargeback resource
mercadopago/sdk-python pull request #56
Opened 2022-02-03 23:29 UTC by matheusfvinhas

2022-02-23 15:02 UTC, eltinMeli commented
Obrigado pela contribuição!

Precisamos que faça um ajuste no seu pull request para que esteja de acordo com nosso guia de contribuição:
- Adicionar descrição com motivação e contexto no pull request

Assim que o fizer, faremos o review.

Abraços

2022-02-24 14:38 UTC, delias-silva commented
Obrigado @matheusfvinhas!

A implementação do seu PR está muito boa.
Só vamos fazer mais alguns testes aqui e depois mergeamos para subir na próxima release.

Abraços.

2022-02-24 14:54 UTC, eltinMeli requested changes

2022-02-24 14:54 UTC, eltinMeli commented on tests/test_chargeback.py
> +from datetime import datetime
@matheusfvinhas o lint está reportando que este import não está sendo usado, poderia remove-lo por favor.

2022-02-24 15:06 UTC, matheusfvinhas commented on tests/test_chargeback.py
> +from datetime import datetime
Feito

2022-02-24 15:36 UTC, eltinMeli commented
Boa @matheusfvinhas, passou no workflow! Seguimos com os testes locais.
 Obrigado

2022-04-01 22:37 UTC, eltinMeli approved these changes

2022-04-01 22:43 UTC, merged