Add plan and subscription resources
mercadopago/sdk-python pull request #60
Opened 2022-09-13 00:25 UTC by gustav0

Hey, before asking for an actual merge, I would like to know about 2 things:

1. Is there any way to delete Plan and Subscription objects? Documentations doesn't show anything about it.
2. Whenever I try to update and existing subscription, I get an 404 error with the following message:
```The template with id {plan_id} does not exist```

Besides that, I believed I could implement a lot more tests, but I don't think they will be useful as our goal is to verify the API calls are being made correctly.

Anything you guys think needs some change, just let me know, and I will get to it.

2022-09-20 18:34 UTC, eltinMeli requested changes

2022-09-20 18:34 UTC, eltinMeli commented on mercadopago/resources/subscription.py
> +        )
Path is incorrect, it is using the path of the plans. 

```suggestion
        return self._put(
            uri="/preapproval/" + str(subscription_id), 
            data=subscription_object, 
            request_options=request_options)
```

2022-09-20 18:34 UTC, eltinMeli commented on tests/test_subscription.py
> +        # self.assertEqual(update_object["reason"], update_payload["reason"])
This must be why the path is wrong, try tweaking and running the test again

2022-09-20 18:37 UTC, eltinMeli commented
@gustav0 thanks for contributing our Python SDK, I left some comments about Lint, link to the docs and a tweak to the path that updates the subscription.

Any doubt, I am available.

Saludos

2022-09-21 00:08 UTC, gustav0 commented
@eltinMeli all set, linting is good and tests are 100% working.

2022-09-21 17:10 UTC, eltinMeli commented
@gustav0 the lint didn't go through a checker that was deprecated, you can remove it in your PR according to this other [PR](https://github.com/mercadopago/sdk-python/pull/61/files) so we can proceed with the approval please.

2022-09-23 15:55 UTC, gustav0 commented
@eltinMeli done.

2022-09-23 22:37 UTC, merged